name: Build with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Update
      run: git submodule update --init --recursive
    - name: Build artifacts
      run: gradle clean build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: build-artifacts
        path: build/libs
